# Generated by Django 4.2.6 on 2023-11-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='Catagory',
        ),
    ]
